// Generated from the Termix terminal command help seed.
// Curated from official manuals plus short, rewritten examples inspired by
// TLDR Pages (CC-BY 4.0) and cheat/cheatsheets (CC0).

export interface TerminalAutocompleteHelp {
  command: string;
  description: string;
  examples: string[];
  category?:
    | "files"
    | "text"
    | "network"
    | "ssh"
    | "system"
    | "packages"
    | "users"
    | "docker"
    | "git";
  risk?: "safe" | "caution" | "dangerous";
  aliases?: string[];
  options?: string[];
  subcommands?: string[];
  globalOptions?: string[];
  commonFormats?: string[];
  commandOptions?: Record<string, string[]>;
  commonPatterns?: Record<string, string[]>;
}

export const TERMINAL_AUTOCOMPLETE_HELP = [
  {
    command: "sudo",
    description: "Befehl mit erhöhten Rechten ausführen",
    examples: ["sudo <command>", "sudo -u www-data <command>", "sudo -i"],
    options: [
      "-E",
      "-H",
      "-k",
      "-K",
      "-l",
      "-n",
      "-S",
      "-s",
      "-u <user>",
      "-g <group>",
      "--preserve-env",
      "--user <user>",
      "--group <group>",
      "--login",
      "--shell",
    ],
  },
  {
    command: "su",
    description: "Zu einem anderen Benutzer oder einer Login-Shell wechseln",
    category: "users",
    risk: "caution",
    examples: [
      "su -",
      "su - root",
      "su - username",
      "su -c 'id' username",
      "su -s /bin/bash www-data",
    ],
    options: [
      "-",
      "-l",
      "-c <command>",
      "-s <shell>",
      "-m",
      "-p",
      "--login",
      "--command <command>",
      "--shell <shell>",
      "--preserve-environment",
    ],
  },
  {
    command: "systemctl",
    description: "systemd Services, Units und Systemzustand verwalten",
    examples: [
      "sudo systemctl status nginx",
      "sudo systemctl restart ssh",
      "sudo systemctl stop apache2",
      "sudo systemctl enable docker --now",
      "systemctl list-units --type service --state running",
      "systemctl list-unit-files --type service",
      "sudo systemctl daemon-reload",
    ],
    options: [
      "--type <service|socket|target|timer|mount>",
      "--state <active|inactive|failed|running|exited>",
      "--failed",
      "--all",
      "--user",
      "--system",
      "--now",
      "--no-pager",
      "--no-legend",
      "--plain",
      "--quiet",
      "--property <name>",
      "--value",
      "--since <time>",
      "--until <time>",
    ],
    subcommands: [
      "status <unit>",
      "start <unit>",
      "stop <unit>",
      "restart <unit>",
      "reload <unit>",
      "try-restart <unit>",
      "reload-or-restart <unit>",
      "enable <unit>",
      "disable <unit>",
      "is-enabled <unit>",
      "is-active <unit>",
      "mask <unit>",
      "unmask <unit>",
      "set-environment <VARIABLE=VALUE>",
      "unset-environment <VARIABLE>",
      "show-environment",
      "import-environment <VARIABLE>",
      "service-watchdogs <BOOL>",
      "switch-root <ROOT> <INIT>",
      "list-units",
      "list-unit-files",
      "list-dependencies <unit>",
      "list-timers",
      "list-sockets",
      "list-jobs",
      "cancel <job>",
      "daemon-reload",
      "daemon-reexec",
      "show <unit>",
      "cat <unit>",
      "edit <unit>",
      "set-property <unit> <PROPERTY=VALUE>",
      "is-failed <unit>",
      "kill <unit>",
      "clean <unit>",
      "reset-failed <unit>",
      "preset <unit>",
      "preset-all",
      "reenable <unit>",
      "link <path>",
      "revert <unit>",
      "add-wants <target> <unit>",
      "add-requires <target> <unit>",
      "get-default",
      "set-default <target>",
      "isolate <target>",
      "reset-failed",
      "reboot",
      "poweroff",
      "halt",
      "suspend",
      "hibernate",
    ],
  },
  {
    command: "journalctl",
    description: "Logs von systemd anzeigen",
    examples: [
      "journalctl -u nginx -f",
      "journalctl -u ssh --since today",
      "journalctl -p err -b",
      "journalctl -n 100 --no-pager",
    ],
    options: [
      "-u <unit>",
      "-f",
      "-n <lines>",
      "-e",
      "-b",
      "-k",
      "-p <priority>",
      "--since <time>",
      "--until <time>",
      "--no-pager",
      "--no-hostname",
      "--utc",
      "-o short",
      "-o short-iso",
      "-o json",
      "-o json-pretty",
    ],
  },
  {
    command: "ip",
    description: "Netzwerkinterfaces, IPs, Routing und Nachbarn verwalten",
    examples: [
      "ip a",
      "ip -br a",
      "ip route",
      "ip route get 8.8.8.8",
      "sudo ip link set eth0 up",
      "sudo ip addr add 192.168.1.50/24 dev eth0",
    ],
    subcommands: [
      "address",
      "addr",
      "a",
      "link",
      "l",
      "route",
      "r",
      "neighbor",
      "neigh",
      "n",
      "rule",
      "tunnel",
      "monitor",
      "netns",
      "maddress",
      "mroute",
    ],
    globalOptions: [
      "-4",
      "-6",
      "-o",
      "-br",
      "-j",
      "-p",
      "-c",
      "-s",
      "-d",
      "-h",
    ],
    commonPatterns: {
      address: [
        "ip a",
        "ip addr show",
        "ip -br a",
        "ip -4 addr show",
        "ip -6 addr show",
        "ip addr show dev <interface>",
        "sudo ip addr add <ip>/<cidr> dev <interface>",
        "sudo ip addr del <ip>/<cidr> dev <interface>",
        "sudo ip addr flush dev <interface>",
      ],
      link: [
        "ip link show",
        "ip -br link",
        "ip link show dev <interface>",
        "sudo ip link set <interface> up",
        "sudo ip link set <interface> down",
        "sudo ip link set <interface> mtu <mtu>",
        "sudo ip link set <interface> name <newname>",
      ],
      route: [
        "ip route",
        "ip route show",
        "ip route get <ip>",
        "sudo ip route add default via <gateway>",
        "sudo ip route add <network>/<cidr> via <gateway>",
        "sudo ip route del default",
        "sudo ip route del <network>/<cidr>",
      ],
      neighbor: ["ip neigh", "ip neigh show", "ip neigh flush all"],
    },
  },
  {
    command: "ifconfig",
    description: "Legacy Netzwerkinterface-Tool",
    examples: [
      "ifconfig",
      "ifconfig -a",
      "sudo ifconfig eth0 up",
      "sudo ifconfig eth0 down",
      "sudo ifconfig eth0 192.168.1.50 netmask 255.255.255.0",
    ],
    options: [
      "-a",
      "-s",
      "-v",
      "up",
      "down",
      "netmask <mask>",
      "broadcast <addr>",
      "mtu <mtu>",
      "promisc",
      "-promisc",
    ],
  },
  {
    command: "ping",
    description: "Host-Erreichbarkeit testen",
    examples: [
      "ping 8.8.8.8",
      "ping -c 4 google.com",
      "ping -4 -c 5 example.com",
      "ping -I eth0 1.1.1.1",
    ],
    options: [
      "-c <count>",
      "-i <interval>",
      "-s <size>",
      "-t <ttl>",
      "-W <timeout>",
      "-w <deadline>",
      "-q",
      "-v",
      "-4",
      "-6",
      "-I <interface>",
      "-M do",
      "-M dont",
      "-M want",
      "-D",
      "-f",
    ],
  },
  {
    command: "ps",
    description: "Prozesse anzeigen",
    examples: [
      "ps aux",
      "ps -ef",
      "ps aux | grep nginx",
      "ps -u www-data",
      "ps -p <pid> -o pid,ppid,user,cmd",
      "ps aux --sort=-%mem",
      "ps aux --sort=-%cpu",
    ],
    options: [
      "aux",
      "ef",
      "elf",
      "-e",
      "-f",
      "-u <user>",
      "-p <pid>",
      "-C <command>",
      "-o <format>",
      "--forest",
      "--sort <field>",
      "--no-headers",
    ],
    commonFormats: [
      "pid,ppid,user,cmd",
      "pid,user,%cpu,%mem,cmd",
      "pid,etime,cmd",
    ],
  },
  {
    command: "top",
    description: "Live-Prozessübersicht",
    examples: ["top", "top -u www-data", "top -p <pid>", "top -b -n 1"],
    options: [
      "-u <user>",
      "-p <pid>",
      "-d <seconds>",
      "-n <iterations>",
      "-b",
      "-H",
      "-o <field>",
    ],
  },
  {
    command: "htop",
    description: "Interaktive Prozessübersicht",
    examples: ["htop", "htop -u root", "htop -p <pid>"],
    options: ["-u <user>", "-p <pid>", "-d <delay>", "-s <column>", "-t"],
  },
  {
    command: "kill",
    description: "Signal an Prozess senden",
    examples: [
      "kill <pid>",
      "kill -9 <pid>",
      "kill -TERM <pid>",
      "kill -HUP <pid>",
    ],
    options: ["-15", "-TERM", "-9", "-KILL", "-1", "-HUP", "-2", "-INT", "-l"],
  },
  {
    command: "pkill",
    description: "Prozesse per Namen beenden",
    examples: [
      "pkill nginx",
      "pkill -f 'python app.py'",
      "pkill -u www-data php",
    ],
    options: ["-f", "-u <user>", "-x", "-9", "-TERM", "-HUP"],
  },
  {
    command: "pgrep",
    description: "Prozess-IDs suchen",
    examples: ["pgrep nginx", "pgrep -af python", "pgrep -u www-data"],
    options: ["-f", "-u <user>", "-x", "-a", "-l", "-n", "-o"],
  },
  {
    command: "netstat",
    description: "Legacy Netzwerkstatus anzeigen",
    examples: ["netstat -tulpn", "netstat -plant", "netstat -rn"],
    options: [
      "-t",
      "-u",
      "-l",
      "-n",
      "-p",
      "-a",
      "-r",
      "-i",
      "-s",
      "-plant",
      "-tulpn",
    ],
  },
  {
    command: "ss",
    description: "Sockets anzeigen, moderner Ersatz für netstat",
    examples: ["ss -tulpn", "ss -ltnp", "ss -tunap", "ss -s"],
    options: [
      "-t",
      "-u",
      "-l",
      "-n",
      "-p",
      "-a",
      "-s",
      "-4",
      "-6",
      "-H",
      "-o",
      "-m",
      "-r",
    ],
  },
  {
    command: "curl",
    description: "HTTP/API Requests und Downloads",
    examples: [
      "curl -I https://example.com",
      "curl -L https://example.com",
      "curl -s https://api.example.com",
      "curl -X POST -H 'Content-Type: application/json' -d '{}' https://api.example.com",
    ],
    options: [
      "-I",
      "-L",
      "-v",
      "-s",
      "-S",
      "-k",
      "-X <method>",
      "-H <header>",
      "-d <data>",
      "-o <file>",
      "-O",
      "-u <user:pass>",
      "--connect-timeout <seconds>",
      "--max-time <seconds>",
      "--retry <count>",
      "--compressed",
      "--http1.1",
      "--http2",
    ],
  },
  {
    command: "wget",
    description: "Dateien herunterladen",
    examples: [
      "wget https://example.com/file.tar.gz",
      "wget -O output.html https://example.com",
      "wget -c https://example.com/bigfile.iso",
    ],
    options: [
      "-O <file>",
      "-q",
      "-c",
      "-r",
      "-np",
      "-N",
      "--timeout <seconds>",
      "--tries <count>",
      "--no-check-certificate",
      "--user <user>",
      "--password <password>",
    ],
  },
  {
    command: "ssh",
    description: "SSH-Verbindung herstellen",
    examples: [
      "ssh user@host",
      "ssh -p 2222 user@host",
      "ssh -i ~/.ssh/id_ed25519 user@host",
      "ssh -L 8080:localhost:80 user@host",
    ],
    options: [
      "-p <port>",
      "-i <identity_file>",
      "-l <user>",
      "-v",
      "-vv",
      "-vvv",
      "-N",
      "-T",
      "-X",
      "-A",
      "-L <local:host:remote>",
      "-R <remote:host:local>",
      "-D <port>",
      "-o <option=value>",
    ],
  },
  {
    command: "scp",
    description: "Dateien über SSH kopieren",
    examples: [
      "scp file.txt user@host:/tmp/",
      "scp -r ./dir user@host:/var/www/",
      "scp -P 2222 file.txt user@host:/tmp/",
    ],
    options: ["-P <port>", "-i <identity_file>", "-r", "-p", "-v", "-C"],
  },
  {
    command: "rsync",
    description: "Dateien synchronisieren",
    examples: [
      "rsync -avz ./dir/ user@host:/backup/dir/",
      "rsync -avz --delete ./site/ user@host:/var/www/site/",
      "rsync -avz -e 'ssh -p 2222' ./dir/ user@host:/tmp/",
      "rsync -avn ./dir/ user@host:/backup/dir/",
      "rsync -av --progress ./large.iso user@host:/tmp/",
      "rsync -av --exclude node_modules ./app/ user@host:/srv/app/",
    ],
    options: [
      "-a",
      "-v",
      "-r",
      "-z",
      "-h",
      "-n",
      "-P",
      "--delete",
      "--progress",
      "--dry-run",
      "--partial",
      "--checksum",
      "--archive",
      "--recursive",
      "--compress",
      "--human-readable",
      "--itemize-changes",
      "--stats",
      "--bwlimit <rate>",
      "-e <ssh command>",
      "--exclude <pattern>",
      "--include <pattern>",
      "--filter <rule>",
      "--files-from <file>",
      "--chmod <mode>",
      "--chown <user:group>",
      "--rsync-path <path>",
      "--protect-args",
    ],
  },
  {
    command: "df",
    description: "Dateisystem-Speicher anzeigen",
    examples: ["df -h", "df -hT", "df -ih"],
    options: ["-h", "-T", "-i", "-a", "-x <type>", "--total"],
  },
  {
    command: "du",
    description: "Speicherverbrauch von Dateien/Ordnern anzeigen",
    examples: ["du -sh *", "du -sh /var/log", "du -h --max-depth=1 /var"],
    options: [
      "-h",
      "-s",
      "-a",
      "-c",
      "-d <depth>",
      "--max-depth=<depth>",
      "--exclude <pattern>",
    ],
  },
  {
    command: "free",
    description: "RAM und Swap anzeigen",
    examples: ["free -h", "free -m", "free -h -s 2"],
    options: ["-h", "-m", "-g", "-s <seconds>", "-t"],
  },
  {
    command: "uptime",
    description: "Laufzeit und Load Average anzeigen",
    examples: ["uptime", "uptime -p", "uptime -s", "uptime --pretty"],
    options: ["-p", "--pretty", "-s", "--since", "-h", "--help", "-V", "--version"],
  },
  {
    command: "lsof",
    description: "Offene Dateien und Ports anzeigen",
    examples: ["lsof -i", "lsof -i :80", "lsof -nP -iTCP -sTCP:LISTEN"],
    options: [
      "-i",
      "-i :<port>",
      "-p <pid>",
      "-u <user>",
      "-n",
      "-P",
      "+D <dir>",
    ],
  },
  {
    command: "find",
    description: "Dateien suchen",
    examples: [
      "find /var/log -type f -name '*.log'",
      "find . -type f -mtime +7",
      "find . -type f -size +100M",
      "find . -name '*.tmp' -delete",
    ],
    options: [
      "-name <pattern>",
      "-iname <pattern>",
      "-type f",
      "-type d",
      "-mtime <days>",
      "-size <size>",
      "-user <user>",
      "-group <group>",
      "-perm <mode>",
      "-exec <command> {} \\;",
      "-delete",
      "-maxdepth <n>",
      "-mindepth <n>",
    ],
  },
  {
    command: "grep",
    description: "Text suchen",
    examples: [
      "grep -i error /var/log/syslog",
      "grep -rn 'TODO' .",
      "grep -C 3 'failed' /var/log/auth.log",
    ],
    options: [
      "-i",
      "-r",
      "-n",
      "-v",
      "-E",
      "-F",
      "-w",
      "-c",
      "-l",
      "-A <lines>",
      "-B <lines>",
      "-C <lines>",
      "--color=auto",
      "--include <glob>",
      "--exclude <glob>",
    ],
  },
  {
    command: "tar",
    description: "Archive erstellen und entpacken",
    examples: [
      "tar -czvf archive.tar.gz ./dir",
      "tar -xzvf archive.tar.gz",
      "tar -xzf archive.tar.gz -C /tmp",
      "tar -tf archive.tar.gz",
      "tar --exclude node_modules -czf app.tar.gz ./app",
      "tar -xJf archive.tar.xz -C /opt/app",
    ],
    options: [
      "-c",
      "-x",
      "-t",
      "-v",
      "-f <file>",
      "-z",
      "-j",
      "-J",
      "-C <dir>",
      "--create",
      "--extract",
      "--list",
      "--file <file>",
      "--gzip",
      "--bzip2",
      "--xz",
      "--directory <dir>",
      "--exclude <pattern>",
      "--strip-components <n>",
      "--wildcards",
      "--numeric-owner",
      "--same-owner",
      "--keep-old-files",
      "--overwrite",
      "--one-file-system",
    ],
  },
  {
    command: "cd",
    description: "Arbeitsverzeichnis wechseln; Shell-Builtin",
    examples: ["cd", "cd ~", "cd /var/www", "cd ..", "cd -"],
  },
  {
    command: "pwd",
    description: "Aktuelles Arbeitsverzeichnis anzeigen",
    examples: ["pwd", "pwd -L", "pwd -P", "pwd --physical"],
    options: ["-L", "--logical", "-P", "--physical"],
  },
  {
    command: "ls",
    description: "Dateien und Verzeichnisse auflisten",
    examples: ["ls", "ls -la", "ls -lah /var/log", "ls -ltr", "ls -lhS"],
    options: [
      "-a",
      "-A",
      "-l",
      "-h",
      "-R",
      "-t",
      "-r",
      "-S",
      "-X",
      "-d",
      "-i",
      "-n",
      "-F",
      "--color=auto",
      "--group-directories-first",
      "--sort <name|size|time|extension>",
      "--time-style <style>",
    ],
  },
  {
    command: "cp",
    description: "Dateien und Verzeichnisse kopieren",
    examples: [
      "cp file.txt backup.txt",
      "cp file.txt /tmp/",
      "cp -r ./dir /tmp/",
      "cp -a /var/www /backup/www",
      "cp -iv *.conf /etc/app/",
      "cp -u source.txt dest.txt",
    ],
    options: [
      "-r",
      "-R",
      "-a",
      "-v",
      "-i",
      "-f",
      "-n",
      "-u",
      "-p",
      "-L",
      "-P",
      "-s",
      "-l",
      "--recursive",
      "--archive",
      "--verbose",
      "--interactive",
      "--force",
      "--no-clobber",
      "--update",
      "--preserve",
      "--parents",
      "--backup",
      "--suffix <suffix>",
      "--target-directory <dir>",
    ],
  },
  {
    command: "mv",
    description: "Dateien und Verzeichnisse verschieben oder umbenennen",
    examples: [
      "mv old.txt new.txt",
      "mv file.txt /tmp/",
      "mv ./dir /opt/",
      "mv -iv *.log /var/log/archive/",
      "mv -n file.txt /tmp/",
      "mv -u source.txt dest.txt",
    ],
    options: [
      "-v",
      "-i",
      "-f",
      "-n",
      "-u",
      "-T",
      "--verbose",
      "--interactive",
      "--force",
      "--no-clobber",
      "--update",
      "--backup",
      "--suffix <suffix>",
      "--target-directory <dir>",
      "--no-target-directory",
    ],
  },
  {
    command: "rm",
    description: "Dateien und Verzeichnisse löschen",
    examples: ["rm file.txt", "rm -i file.txt", "rm -rf ./dir", "rm -v *.tmp"],
    options: [
      "-r",
      "-R",
      "-f",
      "-i",
      "-I",
      "-v",
      "-d",
      "--recursive",
      "--force",
      "--interactive",
      "--verbose",
      "--dir",
      "--preserve-root",
      "--no-preserve-root",
    ],
  },
  {
    command: "mkdir",
    description: "Verzeichnisse erstellen",
    examples: ["mkdir newdir", "mkdir -p /opt/app/data", "mkdir -m 755 public"],
    options: [
      "-p",
      "-v",
      "-m <mode>",
      "--parents",
      "--verbose",
      "--mode <mode>",
    ],
  },
  {
    command: "rmdir",
    description: "Leere Verzeichnisse löschen",
    examples: ["rmdir emptydir", "rmdir -p path/to/emptydir"],
    options: [
      "-p",
      "-v",
      "--parents",
      "--verbose",
      "--ignore-fail-on-non-empty",
    ],
  },
  {
    command: "touch",
    description: "Datei erstellen oder Zeitstempel ändern",
    examples: [
      "touch file.txt",
      "touch -c existing.txt",
      "touch -d '2026-01-01 12:00' file.txt",
    ],
    options: [
      "-a",
      "-m",
      "-c",
      "-d <date>",
      "-t <timestamp>",
      "-r <reference>",
    ],
  },
  {
    command: "ln",
    description: "Hardlinks und symbolische Links erstellen",
    examples: [
      "ln source hardlink",
      "ln -s /opt/app/current /usr/local/bin/app",
      "ln -sfn /opt/releases/v2 /opt/app/current",
    ],
    options: [
      "-s",
      "-f",
      "-n",
      "-v",
      "-T",
      "--symbolic",
      "--force",
      "--no-dereference",
      "--verbose",
      "--target-directory <dir>",
    ],
  },
  {
    command: "readlink",
    description: "Symbolische Links auslesen",
    examples: ["readlink symlink", "readlink -f ./path"],
    options: ["-f", "-e", "-m", "-n", "-v"],
  },
  {
    command: "realpath",
    description: "Absoluten Pfad auflösen",
    examples: [
      "realpath file.txt",
      "realpath --relative-to /var /var/log/syslog",
    ],
    options: [
      "-e",
      "-m",
      "-L",
      "-P",
      "--relative-to <dir>",
      "--relative-base <dir>",
    ],
  },
  {
    command: "basename",
    description: "Dateinamen ohne Pfad ausgeben",
    examples: ["basename /var/log/syslog", "basename /path/file.txt .txt"],
    options: ["-a", "-s <suffix>", "-z"],
  },
  {
    command: "dirname",
    description: "Verzeichnisteil eines Pfads ausgeben",
    examples: ["dirname /var/log/syslog", "dirname ./path/to/file.txt"],
    options: ["-z"],
  },
  {
    command: "file",
    description: "Dateityp erkennen",
    examples: ["file file.txt", "file -i image.png", "file -L symlink"],
    options: ["-b", "-i", "-L", "-z", "-s"],
  },
  {
    command: "stat",
    description: "Datei- oder Dateisystemstatus anzeigen",
    examples: ["stat file.txt", "stat -c '%U %G %a %n' file.txt", "stat -f /"],
    options: ["-c <format>", "-f", "-L", "-t"],
  },
  {
    command: "cat",
    description: "Dateien ausgeben oder zusammenführen",
    examples: [
      "cat file.txt",
      "cat -n file.txt",
      "cat file1 file2 > combined.txt",
    ],
    options: ["-n", "-b", "-A", "-E", "-T", "-s"],
  },
  {
    command: "less",
    description: "Dateien seitenweise anzeigen",
    examples: [
      "less file.txt",
      "less -N /var/log/syslog",
      "less +F /var/log/app.log",
    ],
    options: ["-N", "-S", "-R", "-i", "+F"],
  },
  {
    command: "more",
    description: "Dateien seitenweise anzeigen",
    examples: ["more file.txt", "more /var/log/syslog"],
    options: ["-d", "-f", "-num"],
  },
  {
    command: "nano",
    description: "Datei im Nano-Editor bearbeiten",
    category: "text",
    examples: [
      "nano file.txt",
      "sudo nano /etc/ssh/sshd_config",
      "nano +20 README.md",
    ],
    options: ["-l", "--linenumbers", "-m", "--mouse", "-R", "--restricted"],
  },
  {
    command: "vim",
    description: "Datei im Vim-Editor bearbeiten",
    category: "text",
    aliases: ["vi", "nvim"],
    examples: [
      "vim file.txt",
      "vim ~/.bashrc",
      "sudo vim /etc/fstab",
      "vim +10 README.md",
    ],
    options: ["-R", "-M", "-n", "-p", "-O", "-o", "+<line>"],
  },
  {
    command: "head",
    description: "Anfang einer Datei anzeigen",
    examples: ["head file.txt", "head -n 50 file.txt", "head -c 100 file.txt"],
    options: ["-n <lines>", "-c <bytes>", "-q", "-v"],
  },
  {
    command: "tail",
    description: "Ende einer Datei anzeigen",
    examples: [
      "tail file.txt",
      "tail -n 100 /var/log/syslog",
      "tail -f /var/log/app.log",
      "tail -F /var/log/app.log",
    ],
    options: ["-n <lines>", "-c <bytes>", "-f", "-F", "--pid <pid>", "--retry"],
  },
  {
    command: "wc",
    description: "Zeilen, Wörter und Bytes zählen",
    examples: ["wc file.txt", "wc -l file.txt", "cat file.txt | wc -l"],
    options: ["-l", "-w", "-c", "-m", "-L"],
  },
  {
    command: "sort",
    description: "Zeilen sortieren",
    examples: [
      "sort file.txt",
      "sort -u file.txt",
      "sort -nr numbers.txt",
      "sort -t ':' -k 3 /etc/passwd",
    ],
    options: [
      "-n",
      "-r",
      "-u",
      "-k <key>",
      "-t <separator>",
      "-h",
      "-V",
      "-f",
      "-o <file>",
    ],
  },
  {
    command: "uniq",
    description: "Doppelte benachbarte Zeilen filtern",
    examples: [
      "uniq file.txt",
      "sort file.txt | uniq",
      "sort file.txt | uniq -c",
    ],
    options: ["-c", "-d", "-u", "-i", "-f <fields>", "-s <chars>"],
  },
  {
    command: "cut",
    description: "Spalten oder Zeichenbereiche extrahieren",
    examples: ["cut -d ':' -f 1 /etc/passwd", "cut -c 1-10 file.txt"],
    options: [
      "-d <delimiter>",
      "-f <fields>",
      "-c <chars>",
      "-b <bytes>",
      "--complement",
      "--output-delimiter <delimiter>",
    ],
  },
  {
    command: "awk",
    description: "Textverarbeitung mit Mustern und Aktionen",
    examples: [
      "awk '{print $1}' file.txt",
      "awk -F ':' '{print $1}' /etc/passwd",
      "ps aux | awk '{print $1, $2, $11}'",
      "awk 'NR==1 {print}' file.txt",
      "awk -v limit=10 '$1 > limit {print}' data.txt",
    ],
    options: [
      "-F <separator>",
      "-v <var=value>",
      "-f <script>",
      "--field-separator <separator>",
      "--file <script>",
      "--assign <var=value>",
      "--posix",
      "--lint",
    ],
  },
  {
    command: "sed",
    description: "Stream-Editor für Text-Ersetzungen und Filter",
    examples: [
      "sed 's/foo/bar/g' file.txt",
      "sed -i 's/foo/bar/g' file.txt",
      "sed -n '1,20p' file.txt",
    ],
    options: ["-n", "-i", "-E", "-r", "-e <script>", "-f <scriptfile>"],
  },
  {
    command: "tee",
    description: "Ausgabe gleichzeitig anzeigen und in Datei schreiben",
    examples: [
      "echo test | tee file.txt",
      "echo test | tee -a file.txt",
      "command | sudo tee /etc/app.conf",
      "command | tee file1.log file2.log",
    ],
    options: ["-a", "--append", "-i", "--ignore-interrupts", "-p", "--output-error"],
  },
  {
    command: "xargs",
    description: "Argumentlisten aus stdin bauen",
    examples: [
      "find . -name '*.log' | xargs rm",
      "find . -name '*.log' -print0 | xargs -0 rm",
      "cat hosts.txt | xargs -I {} ping -c 1 {}",
    ],
    options: [
      "-0",
      "-n <number>",
      "-I <replace>",
      "-r",
      "-t",
      "-P <processes>",
      "-L <lines>",
      "-s <size>",
      "-a <file>",
      "--null",
      "--max-args <number>",
      "--replace <replace>",
      "--no-run-if-empty",
      "--verbose",
      "--max-procs <processes>",
      "--arg-file <file>",
    ],
  },
  {
    command: "echo",
    description: "Text ausgeben; oft Shell-Builtin",
    examples: ["echo hello", "echo $PATH", "echo 'text' >> file.txt"],
    options: ["-n", "-e", "-E"],
  },
  {
    command: "printf",
    description: "Formatierten Text ausgeben",
    examples: [
      "printf '%s\\n' hello",
      "printf '%04d\\n' 42",
      "printf '%s=%s\\n' KEY value",
      "printf '%q\\n' \"$PATH\"",
      "printf '%b\\n' 'line1\\nline2'",
    ],
  },
  {
    command: "env",
    description: "Umgebung anzeigen oder Befehl mit Umgebung starten",
    examples: [
      "env",
      "env | grep PATH",
      "env VAR=value command",
      "env -i PATH=/usr/bin:/bin command",
      "env -u DEBUG command",
    ],
    options: [
      "-i",
      "--ignore-environment",
      "-u <name>",
      "--unset <name>",
      "-C <dir>",
      "--chdir <dir>",
      "-S <string>",
      "--split-string <string>",
      "VAR=value",
    ],
  },
  {
    command: "printenv",
    description: "Umgebungsvariablen anzeigen",
    examples: [
      "printenv",
      "printenv PATH",
      "printenv HOME SHELL",
      "printenv | sort",
    ],
    options: ["-0", "--null", "--help", "--version"],
  },
  {
    command: "who",
    description: "angemeldete Benutzer und Sessions anzeigen",
    examples: ["who", "who -a", "who -b", "who -u", "who am i"],
    options: [
      "-a",
      "--all",
      "-b",
      "--boot",
      "-d",
      "--dead",
      "-H",
      "--heading",
      "-m",
      "-q",
      "--count",
      "-r",
      "--runlevel",
      "-u",
      "--users",
    ],
  },
  {
    command: "export",
    description: "Umgebungsvariable setzen; Shell-Builtin",
    examples: ["export VAR=value", "export PATH=$PATH:/opt/bin"],
    options: ["-p", "-n <name>"],
  },
  {
    command: "unset",
    description: "Variable oder Funktion entfernen; Shell-Builtin",
    examples: ["unset VAR", "unset -f function_name"],
    options: ["-v", "-f"],
  },
  {
    command: "alias",
    description: "Shell-Alias anzeigen oder setzen",
    examples: ["alias", "alias ll='ls -lah'"],
  },
  {
    command: "unalias",
    description: "Shell-Alias entfernen",
    examples: ["unalias ll", "unalias -a"],
    options: ["-a"],
  },
  {
    command: "history",
    description: "Shell-History anzeigen oder bearbeiten",
    examples: ["history", "history | grep ssh", "history -c"],
    options: ["-c", "-d <offset>", "-w", "-r"],
  },
  {
    command: "clear",
    description: "Terminal leeren",
    examples: ["clear", "clear -x", "clear -T xterm-256color"],
    options: ["-x", "-T <terminal>", "-V"],
  },
  {
    command: "which",
    description: "Pfad eines Befehls suchen",
    examples: ["which python", "which -a sh"],
    options: ["-a"],
  },
  {
    command: "whereis",
    description: "Binary, Source und Manpage suchen",
    examples: ["whereis nginx", "whereis -b bash"],
    options: ["-b", "-m", "-s"],
  },
  {
    command: "type",
    description: "Befehlstyp in der Shell anzeigen",
    examples: ["type cd", "type -a python"],
    options: ["-a", "-t", "-p"],
  },
  {
    command: "command",
    description: "Shell-Befehl ohne Funktionen/Aliase ausführen oder prüfen",
    examples: ["command -v docker", "command -V cd"],
    options: ["-v", "-V", "-p"],
  },
  {
    command: "gzip",
    description: "Dateien mit gzip komprimieren",
    examples: ["gzip file.txt", "gzip -k file.txt", "gzip -d file.txt.gz"],
    options: ["-d", "-k", "-f", "-v", "-r", "-1", "-9"],
  },
  {
    command: "gunzip",
    description: "gzip-Dateien entpacken",
    examples: ["gunzip file.txt.gz", "gunzip -k file.txt.gz"],
    options: ["-k", "-f", "-v", "-r"],
  },
  {
    command: "zip",
    description: "ZIP-Archive erstellen",
    examples: [
      "zip archive.zip file.txt",
      "zip -r archive.zip ./dir",
      "zip -r archive.zip ./dir -x '*.git*'",
    ],
    options: ["-r", "-q", "-v", "-e", "-9", "-u", "-d", "-x <pattern>"],
  },
  {
    command: "unzip",
    description: "ZIP-Archive entpacken",
    examples: [
      "unzip archive.zip",
      "unzip archive.zip -d /tmp",
      "unzip -l archive.zip",
    ],
    options: ["-l", "-t", "-d <dir>", "-o", "-n", "-q"],
  },
  {
    command: "uname",
    description: "Kernel- und Systeminformationen anzeigen",
    examples: ["uname -a", "uname -r", "uname -m", "uname -n"],
    options: [
      "-a",
      "--all",
      "-s",
      "--kernel-name",
      "-n",
      "--nodename",
      "-r",
      "--kernel-release",
      "-v",
      "--kernel-version",
      "-m",
      "--machine",
      "-p",
      "--processor",
      "-o",
      "--operating-system",
    ],
  },
  {
    command: "hostname",
    description: "Hostname anzeigen oder setzen",
    examples: ["hostname", "hostname -f", "hostname -I", "hostname -A"],
    options: ["-f", "--fqdn", "-s", "--short", "-I", "--all-ip-addresses", "-i", "--ip-address", "-A", "--all-fqdns", "-d", "--domain"],
  },
  {
    command: "hostnamectl",
    description: "System-Hostname und Host-Metadaten verwalten",
    examples: [
      "hostnamectl",
      "hostnamectl status",
      "sudo hostnamectl set-hostname server01",
    ],
    subcommands: [
      "status",
      "set-hostname <hostname>",
      "set-icon-name <name>",
      "set-chassis <type>",
      "set-deployment <environment>",
      "set-location <location>",
    ],
  },
  {
    command: "whoami",
    description: "Aktuellen Benutzer anzeigen",
    examples: ["whoami", "whoami --help", "whoami --version"],
    options: ["--help", "--version"],
  },
  {
    command: "id",
    description: "Benutzer- und Gruppen-IDs anzeigen",
    examples: ["id", "id username", "id -u", "id -Gn"],
    options: [
      "-u",
      "--user",
      "-g",
      "--group",
      "-G",
      "--groups",
      "-n",
      "--name",
      "-r",
      "--real",
      "-z",
      "--zero",
      "-a",
    ],
  },
  {
    command: "groups",
    description: "Gruppen eines Benutzers anzeigen",
    examples: ["groups", "groups username"],
  },
  {
    command: "date",
    description: "Datum und Zeit anzeigen oder formatieren",
    examples: [
      "date",
      "date -u",
      "date -Iseconds",
      "date '+%Y-%m-%d %H:%M:%S'",
      "date -d 'yesterday'",
    ],
    options: [
      "-u",
      "--utc",
      "-R",
      "--rfc-email",
      "-I",
      "--iso-8601",
      "-d <date>",
      "--date <date>",
      "-r <file>",
      "--reference <file>",
      "+<format>",
    ],
  },
  {
    command: "timedatectl",
    description: "Systemzeit und Zeitzone verwalten",
    examples: [
      "timedatectl",
      "timedatectl list-timezones",
      "sudo timedatectl set-timezone Europe/Berlin",
    ],
    subcommands: [
      "status",
      "list-timezones",
      "set-timezone <timezone>",
      "set-time <time>",
      "set-ntp <true|false>",
    ],
  },
  {
    command: "crontab",
    description: "Cronjobs verwalten",
    examples: ["crontab -l", "crontab -e", "sudo crontab -u www-data -l"],
    options: ["-e", "-l", "-r", "-u <user>"],
  },
  {
    command: "mount",
    description: "Dateisysteme einhängen",
    examples: [
      "mount",
      "mount | grep /mnt",
      "sudo mount /dev/sdb1 /mnt",
      "sudo mount -t nfs server:/share /mnt",
    ],
    options: ["-a", "-t <type>", "-o <options>", "-r", "-w", "-v"],
  },
  {
    command: "umount",
    description: "Dateisysteme aushängen",
    examples: ["sudo umount /mnt", "sudo umount -l /mnt"],
    options: ["-a", "-f", "-l", "-v"],
  },
  {
    command: "lsblk",
    description: "Blockgeräte anzeigen",
    examples: ["lsblk", "lsblk -f", "lsblk -o NAME,SIZE,FSTYPE,MOUNTPOINT"],
    options: ["-f", "-a", "-o <columns>", "-p", "-J"],
  },
  {
    command: "blkid",
    description: "Blockgeräte-UUIDs und Dateisystemtypen anzeigen",
    examples: ["blkid", "sudo blkid /dev/sda1"],
    options: ["-o <format>", "-s <tag>", "-L <label>", "-U <uuid>"],
  },
  {
    command: "nc",
    description: "Netcat: TCP/UDP-Verbindungen testen",
    examples: ["nc -vz host 22", "nc -l -p 8080", "nc -u host 53"],
    options: [
      "-l",
      "-p <port>",
      "-v",
      "-z",
      "-u",
      "-w <seconds>",
      "-n",
      "-4",
      "-6",
    ],
  },
  {
    command: "dig",
    description: "DNS-Abfragen ausführen",
    examples: [
      "dig example.com",
      "dig +short example.com",
      "dig @1.1.1.1 example.com A",
      "dig -x 8.8.8.8",
    ],
    options: ["+short", "+trace", "+noall", "+answer", "@<server>", "-x <ip>"],
  },
  {
    command: "nslookup",
    description: "DNS-Abfragen, legacy aber noch verbreitet",
    examples: [
      "nslookup example.com",
      "nslookup example.com 1.1.1.1",
      "nslookup -type=MX example.com",
    ],
  },
  {
    command: "traceroute",
    description: "Route zu einem Host verfolgen",
    examples: [
      "traceroute example.com",
      "traceroute -n 8.8.8.8",
      "traceroute -T -p 443 example.com",
    ],
    options: [
      "-n",
      "-I",
      "-T",
      "-p <port>",
      "-m <max_hops>",
      "-q <queries>",
      "-w <seconds>",
    ],
  },
  {
    command: "tracepath",
    description: "Route ohne Root-Rechte verfolgen",
    examples: ["tracepath example.com", "tracepath -n 8.8.8.8"],
    options: ["-n", "-b", "-l <length>", "-m <max_hops>"],
  },
  {
    command: "mtr",
    description: "Ping und Traceroute kombiniert",
    examples: [
      "mtr example.com",
      "mtr -rw -c 100 example.com",
      "mtr -T -P 443 example.com",
    ],
    options: ["-r", "-w", "-c <count>", "-n", "-4", "-6", "-T", "-u"],
  },
  {
    command: "ufw",
    description: "Ubuntu Firewall verwalten",
    examples: [
      "sudo ufw status",
      "sudo ufw status verbose",
      "sudo ufw allow 22/tcp",
      "sudo ufw allow from 192.168.1.0/24",
      "sudo ufw delete allow 80/tcp",
    ],
    subcommands: [
      "status",
      "status verbose",
      "enable",
      "disable",
      "reload",
      "allow <port>",
      "deny <port>",
      "delete allow <port>",
      "delete deny <port>",
      "allow from <ip>",
      "deny from <ip>",
    ],
  },
  {
    command: "iptables",
    description: "Legacy Linux Firewall-Regeln verwalten",
    examples: [
      "sudo iptables -L -n -v",
      "sudo iptables -S",
      "sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT",
      "sudo iptables -F",
    ],
    options: [
      "-L",
      "-S",
      "-A <chain>",
      "-I <chain>",
      "-D <chain>",
      "-F",
      "-t <table>",
      "-p <protocol>",
      "-s <source>",
      "-d <destination>",
      "--dport <port>",
      "--sport <port>",
      "-j <target>",
      "-n",
      "-v",
    ],
  },
  {
    command: "nft",
    description: "nftables Firewall verwalten",
    examples: [
      "sudo nft list ruleset",
      "sudo nft list tables",
      "sudo nft flush ruleset",
    ],
    subcommands: [
      "list ruleset",
      "list tables",
      "list table <family> <table>",
      "add table <family> <table>",
      "add chain <family> <table> <chain>",
      "add rule <family> <table> <chain> <rule>",
      "delete rule <family> <table> <chain> handle <handle>",
      "flush ruleset",
    ],
  },
  {
    command: "chmod",
    description: "Dateirechte ändern",
    examples: [
      "chmod +x script.sh",
      "chmod 644 file.txt",
      "chmod 755 directory",
      "chmod -R 755 /var/www",
    ],
  },
  {
    command: "chown",
    description: "Dateibesitzer ändern",
    examples: [
      "sudo chown user:group file",
      "sudo chown -R www-data:www-data /var/www",
    ],
    options: ["-R", "-v", "-c"],
  },
  {
    command: "useradd",
    description: "Benutzer erstellen",
    examples: [
      "sudo useradd -m -s /bin/bash username",
      "sudo useradd -m -G sudo username",
    ],
    options: ["-m", "-s <shell>", "-G <groups>", "-u <uid>", "-d <home>"],
  },
  {
    command: "usermod",
    description: "Benutzer ändern",
    examples: [
      "sudo usermod -aG sudo username",
      "sudo usermod -s /bin/bash username",
    ],
    options: ["-aG <groups>", "-s <shell>", "-d <home>", "-L", "-U"],
  },
  {
    command: "passwd",
    description: "Passwort ändern",
    examples: [
      "passwd",
      "sudo passwd username",
      "sudo passwd -S username",
      "sudo passwd -l username",
    ],
    options: ["-S", "--status", "-l", "--lock", "-u", "--unlock", "-d", "--delete", "-e", "--expire", "-n <days>", "--mindays <days>", "-x <days>", "--maxdays <days>", "-w <days>", "--warndays <days>"],
  },
  {
    command: "apt",
    description: "Debian/Ubuntu Paketverwaltung",
    examples: [
      "sudo apt update",
      "sudo apt upgrade -y",
      "sudo apt install nginx",
      "apt search docker",
      "apt show nginx",
    ],
    options: ["-y", "--no-install-recommends", "--reinstall", "--only-upgrade"],
    subcommands: [
      "update",
      "upgrade",
      "full-upgrade",
      "install <package>",
      "remove <package>",
      "purge <package>",
      "autoremove",
      "autoclean",
      "search <term>",
      "show <package>",
      "list --installed",
    ],
  },
  {
    command: "docker",
    description: "Docker Container, Images, Volumes und Networks verwalten",
    examples: [
      "docker ps",
      "docker ps -a",
      "docker images",
      "docker pull nginx",
      "docker run -d --name web -p 8080:80 nginx",
      "docker logs -f web",
      "docker exec -it web /bin/bash",
      "docker stop web",
      "docker restart web",
      "docker rm -f web",
      "docker build -t myapp:latest .",
      "docker system df",
      "docker system prune -af",
      "docker compose up -d",
      "docker compose down",
      "docker compose logs -f",
      "docker compose exec app sh",
    ],
    subcommands: [
      "ps",
      "ps -a",
      "images",
      "pull <image>",
      "push <image>",
      "build <path>",
      "run <image>",
      "start <container>",
      "stop <container>",
      "restart <container>",
      "rm <container>",
      "rmi <image>",
      "logs <container>",
      "exec <container> <command>",
      "inspect <object>",
      "stats",
      "top <container>",
      "cp <src> <dest>",
      "network ls",
      "network create <name>",
      "network inspect <name>",
      "network rm <name>",
      "volume ls",
      "volume create <name>",
      "volume inspect <name>",
      "volume rm <name>",
      "compose up",
      "compose down",
      "compose ps",
      "compose logs",
      "compose exec",
      "compose build",
      "compose pull",
      "compose restart",
      "system df",
      "system prune",
    ],
    globalOptions: [
      "--config <dir>",
      "-D",
      "--debug",
      "-H <host>",
      "--host <host>",
      "--tls",
      "--tlscacert <file>",
      "--tlscert <file>",
      "--tlskey <file>",
      "--tlsverify",
      "-v",
      "--version",
    ],
    commandOptions: {
      ps: [
        "-a",
        "--all",
        "-q",
        "--quiet",
        "--filter <filter>",
        "--format <format>",
        "--no-trunc",
        "--size",
      ],
      run: [
        "-d",
        "-it",
        "--name <name>",
        "-p <host:container>",
        "--publish <host:container>",
        "-v <host:container>",
        "--volume <host:container>",
        "-e <key=value>",
        "--env <key=value>",
        "--env-file <file>",
        "--rm",
        "--restart <no|always|unless-stopped|on-failure>",
        "--network <network>",
        "--hostname <name>",
        "--add-host <host:ip>",
        "--dns <ip>",
        "--entrypoint <command>",
        "-w <dir>",
        "--workdir <dir>",
        "-u <user>",
        "--user <user>",
        "--privileged",
        "--cap-add <capability>",
        "--cap-drop <capability>",
        "--memory <limit>",
        "--cpus <number>",
        "--pull <always|missing|never>",
      ],
      logs: [
        "-f",
        "--follow",
        "--tail <lines>",
        "--since <time>",
        "--until <time>",
        "-t",
        "--timestamps",
        "--details",
      ],
      exec: [
        "-it",
        "-i",
        "-t",
        "-u <user>",
        "-w <dir>",
        "-e <key=value>",
        "--privileged",
      ],
      build: [
        "-t <name:tag>",
        "-f <Dockerfile>",
        "--build-arg <key=value>",
        "--no-cache",
        "--pull",
        "--target <stage>",
        "--progress <auto|plain|tty>",
      ],
      stop: ["-t <seconds>", "--time <seconds>"],
      rm: ["-f", "-v", "-l"],
      rmi: ["-f", "--no-prune"],
      inspect: ["-f <format>", "--format <format>", "--size"],
      stats: ["--no-stream", "--format <format>", "--all"],
      system_prune: ["-a", "-f", "--volumes"],
      compose: ["-f <file>", "-p <project>", "--profile <profile>"],
    },
  },
  {
    command: "docker compose",
    description: "Docker Compose Projekte verwalten",
    examples: [
      "docker compose up -d",
      "docker compose down",
      "docker compose logs -f",
      "docker compose exec app sh",
      "docker compose build --no-cache",
      "docker compose pull",
    ],
    options: [
      "-f <compose-file>",
      "-p <project-name>",
      "--profile <profile>",
      "--env-file <file>",
    ],
    subcommands: [
      "up",
      "up -d",
      "down",
      "ps",
      "logs",
      "exec <service> <command>",
      "run <service> <command>",
      "build",
      "pull",
      "restart",
      "stop",
      "start",
      "rm",
      "config",
      "images",
      "top",
    ],
    commandOptions: {
      up: [
        "-d",
        "--build",
        "--force-recreate",
        "--remove-orphans",
        "--pull <always|missing|never>",
        "--scale <service=num>",
      ],
      down: ["-v", "--remove-orphans", "--rmi <local|all>"],
      logs: ["-f", "--tail <lines>", "-t"],
      exec: ["-it", "-u <user>", "-w <dir>", "-e <key=value>"],
      build: ["--no-cache", "--pull", "--progress <auto|plain|tty>"],
    },
  },
  {
    command: "git",
    description: "Versionsverwaltung",
    examples: [
      "git status",
      "git pull",
      "git add .",
      "git commit -m 'message'",
      "git log --oneline --graph --decorate --all",
    ],
    options: ["--help", "-C <path>"],
    subcommands: [
      "status",
      "clone <repo>",
      "init",
      "pull",
      "push",
      "fetch",
      "checkout <branch>",
      "switch <branch>",
      "branch",
      "branch -a",
      "add <file>",
      "mv <source> <destination>",
      "restore <path>",
      "rm <path>",
      "commit",
      "commit -m <message>",
      "log",
      "diff",
      "grep <pattern>",
      "show <object>",
      "stash",
      "stash pop",
      "merge <branch>",
      "rebase <branch>",
      "reset <commit>",
      "revert <commit>",
      "cherry-pick <commit>",
      "tag",
      "tag <name>",
      "bisect",
      "remote -v",
      "remote add origin <url>",
      "remote set-url origin <url>",
      "worktree list",
      "worktree add <path> <branch>",
      "worktree remove <path>",
      "submodule status",
      "submodule update --init --recursive",
      "config --list",
      "config user.name",
      "config user.email",
      "clean -n",
      "clean -i",
      "blame <file>",
      "describe --tags",
      "ls-files",
      "ls-remote <repo>",
      "reflog",
      "rev-parse --show-toplevel",
      "shortlog -sn",
      "archive --format=tar --output <file> HEAD",
    ],
    commandOptions: {
      status: ["--short", "--branch", "--porcelain", "--ignored"],
      clone: ["--branch <branch>", "--depth <depth>", "--recurse-submodules"],
      init: ["--bare", "--initial-branch <branch>"],
      add: ["-A", "-p", "--all", "--patch"],
      restore: ["--staged", "--source <tree>", "--worktree"],
      rm: ["--cached", "-r", "-f"],
      commit: ["-m <message>", "--amend", "--no-edit", "--all"],
      log: ["--oneline", "--graph", "--decorate", "--all", "-p"],
      diff: ["--staged", "--stat", "--name-only", "--word-diff"],
      branch: ["-a", "-d <branch>", "-D <branch>", "--merged"],
      checkout: ["-b <branch>", "-- <path>"],
      switch: ["-c <branch>", "--detach"],
      reset: ["--soft", "--mixed", "--keep", "--merge"],
      stash: ["list", "pop", "apply", "push -m <message>", "drop"],
      merge: ["--no-ff", "--squash", "--abort"],
      rebase: ["--continue", "--abort", "--interactive"],
      revert: ["--no-edit", "--continue", "--abort"],
      "cherry-pick": ["--continue", "--abort", "--no-commit"],
      tag: ["-a <name>", "-d <name>", "-l"],
      remote: ["-v", "add origin <url>", "set-url origin <url>"],
      worktree: ["list", "add <path> <branch>", "remove <path>", "prune"],
      submodule: ["status", "init", "update --init --recursive", "foreach <command>"],
      config: [
        "--list",
        "--global user.name <name>",
        "--global user.email <email>",
        "--get <key>",
      ],
      clean: ["-n", "-i", "-d -n"],
      blame: ["-L <start>,<end>", "-w"],
      describe: ["--tags", "--always", "--dirty"],
      "ls-files": ["--stage", "--others", "--ignored", "--exclude-standard"],
      "ls-remote": ["--heads", "--tags"],
      reflog: ["show", "expire --dry-run"],
      "rev-parse": ["--show-toplevel", "--abbrev-ref HEAD"],
      shortlog: ["-sn", "--all"],
      archive: ["--format=tar", "--format=zip", "--output <file>"],
      fetch: ["--all", "--prune", "--tags"],
      pull: ["--rebase", "--ff-only"],
      push: ["--set-upstream origin <branch>", "--tags", "--force-with-lease"],
    },
  },
  {
    command: "diff",
    description: "Dateien zeilenweise vergleichen",
    category: "text",
    risk: "safe",
    examples: [
      "diff old.txt new.txt",
      "diff -u old.txt new.txt",
      "diff -r dir-a dir-b",
    ],
    options: [
      "-u",
      "--unified",
      "-r",
      "--recursive",
      "-q",
      "--brief",
      "-y",
      "--side-by-side",
      "-w",
      "--ignore-all-space",
      "-B",
      "--ignore-blank-lines",
    ],
  },
  {
    command: "patch",
    description: "Änderungen aus Patch-Dateien anwenden",
    category: "text",
    risk: "caution",
    examples: [
      "patch < fix.patch",
      "patch -p1 < changes.patch",
      "patch --dry-run -p1 < changes.patch",
    ],
    options: [
      "-p <num>",
      "--strip <num>",
      "--dry-run",
      "-R",
      "--reverse",
      "-i <file>",
      "--input <file>",
      "-d <dir>",
      "--directory <dir>",
    ],
  },
  {
    command: "cmp",
    description: "Dateien bytegenau vergleichen",
    category: "text",
    risk: "safe",
    examples: [
      "cmp file-a file-b",
      "cmp -l file-a file-b",
      "cmp -s file-a file-b",
    ],
    options: ["-b", "--print-bytes", "-l", "--verbose", "-s", "--quiet"],
  },
  {
    command: "tr",
    description: "Zeichen übersetzen, löschen oder zusammenfassen",
    category: "text",
    risk: "safe",
    examples: [
      "echo hello | tr a-z A-Z",
      "tr -d '\\r' < windows.txt > unix.txt",
      "tr -s ' ' < file.txt",
    ],
    options: [
      "-d",
      "--delete",
      "-s",
      "--squeeze-repeats",
      "-c",
      "--complement",
    ],
  },
  {
    command: "nl",
    description: "Zeilen nummerieren",
    category: "text",
    risk: "safe",
    examples: ["nl file.txt", "nl -ba file.txt", "nl -w1 -s': ' file.txt"],
    options: [
      "-b <style>",
      "--body-numbering <style>",
      "-w <num>",
      "--number-width <num>",
      "-s <sep>",
      "--number-separator <sep>",
    ],
  },
  {
    command: "split",
    description: "Dateien in kleinere Teile aufteilen",
    category: "files",
    risk: "safe",
    examples: [
      "split -l 1000 big.log part-",
      "split -b 100M archive.tar archive.part.",
      "split -d -a 3 file chunk-",
    ],
    options: [
      "-l <lines>",
      "--lines <lines>",
      "-b <size>",
      "--bytes <size>",
      "-d",
      "--numeric-suffixes",
      "-a <length>",
      "--suffix-length <length>",
    ],
  },
  {
    command: "paste",
    description: "Zeilen mehrerer Dateien nebeneinander zusammenführen",
    category: "text",
    risk: "safe",
    examples: [
      "paste names.txt values.txt",
      "paste -d ',' a.txt b.txt",
      "paste -s file.txt",
    ],
    options: [
      "-d <list>",
      "--delimiters <list>",
      "-s",
      "--serial",
      "-z",
      "--zero-terminated",
    ],
  },
  {
    command: "column",
    description: "Tabellen lesbar ausrichten",
    category: "text",
    risk: "safe",
    examples: [
      "column -t table.txt",
      "cat data.csv | column -s, -t",
      "mount | column -t",
    ],
    options: [
      "-t",
      "--table",
      "-s <sep>",
      "--separator <sep>",
      "-N <names>",
      "--table-columns <names>",
      "-o <sep>",
      "--output-separator <sep>",
    ],
  },
  {
    command: "jq",
    description: "JSON filtern und formatieren",
    category: "text",
    risk: "safe",
    examples: [
      "jq . data.json",
      "jq '.items[] | .name' data.json",
      "curl -s https://example/api | jq .",
    ],
    options: [
      "-r",
      "--raw-output",
      "-c",
      "--compact-output",
      "-s",
      "--slurp",
      "-e",
      "--exit-status",
      "--arg <name> <value>",
    ],
  },
  {
    command: "watch",
    description: "Befehl regelmäßig neu ausführen",
    category: "system",
    risk: "safe",
    examples: [
      "watch -n 1 date",
      "watch -d 'df -h'",
      "watch -n 2 'systemctl status ssh'",
    ],
    options: [
      "-n <seconds>",
      "--interval <seconds>",
      "-d",
      "--differences",
      "-t",
      "--no-title",
      "-c",
      "--color",
    ],
  },
  {
    command: "timeout",
    description: "Befehl nach einer Zeitgrenze beenden",
    category: "system",
    risk: "safe",
    examples: [
      "timeout 10s ping 8.8.8.8",
      "timeout -k 5s 1m long-command",
      "timeout --preserve-status 30s script.sh",
    ],
    options: [
      "-k <duration>",
      "--kill-after <duration>",
      "-s <signal>",
      "--signal <signal>",
      "--preserve-status",
      "-v",
      "--verbose",
    ],
  },
  {
    command: "yes",
    description: "Text fortlaufend ausgeben",
    category: "text",
    risk: "caution",
    examples: ["yes", "yes n | command", "yes 'test' | head"],
    options: ["--help", "--version"],
  },
  {
    command: "seq",
    description: "Zahlenfolgen ausgeben",
    category: "text",
    risk: "safe",
    examples: ["seq 5", "seq 1 2 10", "seq -w 001 010"],
    options: [
      "-f <format>",
      "--format <format>",
      "-s <sep>",
      "--separator <sep>",
      "-w",
      "--equal-width",
    ],
  },
  {
    command: "sha256sum",
    description: "SHA-256 Prüfsummen berechnen oder prüfen",
    category: "files",
    risk: "safe",
    examples: [
      "sha256sum file.iso",
      "sha256sum -c checksums.txt",
      "find . -type f -print0 | xargs -0 sha256sum",
    ],
    options: [
      "-c",
      "--check",
      "-b",
      "--binary",
      "-t",
      "--text",
      "--quiet",
      "--status",
    ],
  },
  {
    command: "sha1sum",
    description: "SHA-1 Prüfsummen berechnen oder prüfen",
    category: "files",
    risk: "safe",
    examples: ["sha1sum file.iso", "sha1sum -c checksums.txt"],
    options: [
      "-c",
      "--check",
      "-b",
      "--binary",
      "-t",
      "--text",
      "--quiet",
      "--status",
    ],
  },
  {
    command: "md5sum",
    description: "MD5 Prüfsummen berechnen oder prüfen",
    category: "files",
    risk: "safe",
    examples: ["md5sum file.iso", "md5sum -c checksums.txt"],
    options: [
      "-c",
      "--check",
      "-b",
      "--binary",
      "-t",
      "--text",
      "--quiet",
      "--status",
    ],
  },
  {
    command: "base64",
    description: "Daten als Base64 kodieren oder dekodieren",
    category: "text",
    risk: "safe",
    examples: [
      "base64 file.bin",
      "echo text | base64",
      "base64 -d encoded.txt",
    ],
    options: [
      "-d",
      "--decode",
      "-w <cols>",
      "--wrap <cols>",
      "-i",
      "--ignore-garbage",
    ],
  },
  {
    command: "hexdump",
    description: "Dateien hexadezimal anzeigen",
    category: "files",
    risk: "safe",
    examples: [
      "hexdump -C file.bin",
      "hexdump -n 64 file.bin",
      "echo test | hexdump -C",
    ],
    options: [
      "-C",
      "--canonical",
      "-n <length>",
      "--length <length>",
      "-s <offset>",
      "--skip <offset>",
      "-v",
      "--no-squeezing",
    ],
  },
  {
    command: "xxd",
    description: "Hexdump erzeugen oder zurückwandeln",
    category: "files",
    risk: "safe",
    examples: [
      "xxd file.bin",
      "xxd -l 64 file.bin",
      "xxd -r dump.hex file.bin",
    ],
    options: ["-r", "-p", "-l <len>", "-s <seek>", "-c <cols>", "-g <bytes>"],
  },
  {
    command: "dd",
    description: "Daten blockweise kopieren und konvertieren",
    category: "files",
    risk: "dangerous",
    examples: [
      "dd if=input.img of=output.img bs=4M status=progress",
      "dd if=/dev/zero of=test.img bs=1M count=100",
      "dd if=disk.img of=/dev/sdX bs=4M status=progress",
    ],
    options: [
      "if=<file>",
      "of=<file>",
      "bs=<size>",
      "count=<n>",
      "status=progress",
      "conv=fsync",
      "conv=noerror,sync",
    ],
  },
  {
    command: "install",
    description: "Dateien kopieren und Rechte setzen",
    category: "files",
    risk: "caution",
    examples: [
      "install -m 755 app /usr/local/bin/app",
      "install -d -m 755 /opt/app",
      "install -o root -g root file /etc/app/file",
    ],
    options: [
      "-m <mode>",
      "--mode <mode>",
      "-d",
      "--directory",
      "-o <owner>",
      "--owner <owner>",
      "-g <group>",
      "--group <group>",
      "-D",
    ],
  },
  {
    command: "shred",
    description: "Dateiinhalte überschreiben",
    category: "files",
    risk: "dangerous",
    examples: ["shred file.txt", "shred -v -n 3 file.txt", "shred -u file.txt"],
    options: [
      "-v",
      "--verbose",
      "-n <count>",
      "--iterations <count>",
      "-u",
      "--remove",
      "-z",
      "--zero",
    ],
  },
  {
    command: "ssh-keygen",
    description: "SSH-Schlüssel erzeugen und verwalten",
    category: "ssh",
    risk: "safe",
    examples: [
      "ssh-keygen -t ed25519 -C 'user@example.com'",
      "ssh-keygen -R 192.168.1.10",
      "ssh-keygen -lf ~/.ssh/id_ed25519.pub",
    ],
    options: [
      "-t <type>",
      "-C <comment>",
      "-f <file>",
      "-N <passphrase>",
      "-R <host>",
      "-l",
      "-F <host>",
      "-y",
      "-p",
    ],
  },
  {
    command: "ssh-copy-id",
    description: "SSH-Public-Key auf einen Server kopieren",
    category: "ssh",
    risk: "safe",
    examples: [
      "ssh-copy-id user@host",
      "ssh-copy-id -i ~/.ssh/id_ed25519.pub pi@raspberrypi",
      "ssh-copy-id -p 2222 user@host",
      "ssh-copy-id -o StrictHostKeyChecking=accept-new user@host",
      "ssh-copy-id -f -i ~/.ssh/deploy.pub deploy@host",
    ],
    options: [
      "-i <identity_file>",
      "-p <port>",
      "-f",
      "-n",
      "-s",
      "-o <option>",
      "-h",
      "--help",
    ],
  },
  {
    command: "ssh-agent",
    description: "SSH-Agent für Schlüssel starten",
    category: "ssh",
    risk: "safe",
    examples: [
      "eval $(ssh-agent)",
      "ssh-agent bash",
      "ssh-agent -s",
      "ssh-agent -k",
      "ssh-agent -t 1h",
    ],
    options: ["-s", "-c", "-k", "-a <bind_address>", "-t <life>", "-D", "-d"],
  },
  {
    command: "ssh-add",
    description: "SSH-Schlüssel in den Agent laden",
    category: "ssh",
    risk: "safe",
    examples: [
      "ssh-add ~/.ssh/id_ed25519",
      "ssh-add -l",
      "ssh-add -L",
      "ssh-add -D",
      "ssh-add -t 1h ~/.ssh/id_ed25519",
    ],
    options: ["-l", "-L", "-D", "-d", "-t <life>", "-K", "-q", "-v", "-c", "-k", "-x", "-X", "-s <pkcs11_provider>", "-e <pkcs11_provider>", "-T <pubkey_file>"],
  },
  {
    command: "ssh-keyscan",
    description: "SSH-Host-Keys einsammeln",
    category: "ssh",
    risk: "safe",
    examples: [
      "ssh-keyscan github.com",
      "ssh-keyscan -p 2222 host",
      "ssh-keyscan -H host >> ~/.ssh/known_hosts",
    ],
    options: ["-p <port>", "-t <type>", "-H", "-T <timeout>", "-4", "-6"],
  },
  {
    command: "sftp",
    description: "Dateien über SSH interaktiv übertragen",
    category: "ssh",
    risk: "safe",
    examples: [
      "sftp user@host",
      "sftp -P 2222 user@host",
      "sftp -i ~/.ssh/id_ed25519 user@host",
      "sftp -b upload.batch user@host",
      "sftp -J bastion user@host",
    ],
    options: [
      "-P <port>",
      "-i <identity_file>",
      "-b <batchfile>",
      "-o <option>",
      "-F <ssh_config>",
      "-J <jump_host>",
      "-l <limit>",
      "-B <buffer_size>",
      "-R <num_requests>",
      "-S <ssh_program>",
      "-4",
      "-6",
      "-q",
      "-v",
      "-r",
      "-C",
    ],
  },
  {
    command: "apt-get",
    description: "Debian/Ubuntu Pakete skriptfreundlich verwalten",
    category: "packages",
    risk: "caution",
    examples: [
      "sudo apt-get update",
      "sudo apt-get install nginx",
      "sudo apt-get autoremove",
    ],
    options: [
      "-y",
      "--yes",
      "-s",
      "--simulate",
      "--no-install-recommends",
      "-f",
      "--fix-broken",
      "-q",
      "--quiet",
    ],
    subcommands: [
      "update",
      "upgrade",
      "install <package>",
      "remove <package>",
      "purge <package>",
      "autoremove",
      "dist-upgrade",
    ],
  },
  {
    command: "apt-cache",
    description: "APT-Paketinformationen durchsuchen",
    category: "packages",
    risk: "safe",
    examples: [
      "apt-cache search nginx",
      "apt-cache policy nginx",
      "apt-cache show nginx",
    ],
    options: ["--names-only", "--no-all-versions", "-q", "--quiet"],
    subcommands: [
      "search <term>",
      "show <package>",
      "policy <package>",
      "depends <package>",
      "rdepends <package>",
    ],
  },
  {
    command: "dpkg",
    description: "Debian-Pakete lokal abfragen und installieren",
    category: "packages",
    risk: "caution",
    examples: [
      "dpkg -l",
      "dpkg -L nginx",
      "dpkg -s nginx",
      "dpkg --contents package.deb",
      "dpkg --info package.deb",
      "sudo dpkg -i package.deb",
    ],
    options: [
      "-i <package.deb>",
      "--install <package.deb>",
      "--unpack <package.deb>",
      "-l",
      "--list",
      "-L <package>",
      "--listfiles <package>",
      "-s <package>",
      "--status <package>",
      "-S <pattern>",
      "--search <pattern>",
      "-c <package.deb>",
      "--contents <package.deb>",
      "-I <package.deb>",
      "--info <package.deb>",
      "--configure <package>",
      "--audit",
      "--verify <package>",
      "--get-selections",
      "--print-architecture",
    ],
  },
  {
    command: "dmesg",
    description: "Kernel-Meldungen anzeigen",
    category: "system",
    risk: "safe",
    examples: ["dmesg", "dmesg -T", "dmesg -w"],
    options: [
      "-T",
      "--ctime",
      "-w",
      "--follow",
      "-H",
      "--human",
      "-l <level>",
      "--level <level>",
      "-k",
      "--kernel",
    ],
  },
  {
    command: "sysctl",
    description: "Kernel-Parameter anzeigen und setzen",
    category: "system",
    risk: "caution",
    examples: [
      "sysctl -a",
      "sysctl net.ipv4.ip_forward",
      "sudo sysctl -w net.ipv4.ip_forward=1",
    ],
    options: [
      "-a",
      "--all",
      "-w",
      "--write",
      "-p <file>",
      "--load <file>",
      "-n",
      "--values",
    ],
  },
  {
    command: "findmnt",
    description: "Mountpoints und Dateisysteme anzeigen",
    category: "system",
    risk: "safe",
    examples: ["findmnt", "findmnt /", "findmnt -t ext4"],
    options: [
      "-t <type>",
      "--types <type>",
      "-S <source>",
      "--source <source>",
      "-T <path>",
      "--target <path>",
      "-J",
      "--json",
      "-R",
      "--submounts",
    ],
  },
  {
    command: "loginctl",
    description: "systemd-Logins, Sessions und Seats verwalten",
    category: "system",
    risk: "caution",
    examples: [
      "loginctl",
      "loginctl list-sessions",
      "loginctl show-user $USER",
    ],
    options: [
      "--no-pager",
      "--no-legend",
      "--property <name>",
      "--value",
      "--user",
    ],
    subcommands: [
      "list-sessions",
      "session-status <id>",
      "show-session <id>",
      "list-users",
      "show-user <user>",
      "terminate-session <id>",
    ],
  },
  {
    command: "systemd-analyze",
    description: "Bootzeit und systemd-Abhängigkeiten analysieren",
    category: "system",
    risk: "safe",
    examples: [
      "systemd-analyze",
      "systemd-analyze blame",
      "systemd-analyze critical-chain",
    ],
    options: [
      "--user",
      "--system",
      "--no-pager",
      "--json <mode>",
      "--order <order>",
    ],
    subcommands: [
      "time",
      "blame",
      "critical-chain",
      "plot",
      "dot",
      "verify <unit>",
    ],
  },
  {
    command: "service",
    description: "SysV/Systemdienste steuern",
    category: "system",
    risk: "caution",
    examples: [
      "service --status-all",
      "sudo service ssh status",
      "sudo service nginx restart",
    ],
    options: ["--status-all", "--help", "--version"],
    subcommands: [
      "<service> status",
      "<service> start",
      "<service> stop",
      "<service> restart",
      "<service> reload",
    ],
  },
  {
    command: "update-alternatives",
    description: "Standardprogramme über Alternativen verwalten",
    category: "system",
    risk: "caution",
    examples: [
      "update-alternatives --display editor",
      "sudo update-alternatives --config java",
      "sudo update-alternatives --install /usr/bin/editor editor /usr/bin/vim 100",
    ],
    options: [
      "--display <name>",
      "--config <name>",
      "--list <name>",
      "--install <link> <name> <path> <priority>",
      "--remove <name> <path>",
      "--auto <name>",
      "--set <name> <path>",
    ],
  },
  {
    command: "chgrp",
    description: "Gruppenbesitz von Dateien ändern",
    category: "users",
    risk: "caution",
    examples: [
      "chgrp www-data file.txt",
      "sudo chgrp -R www-data /var/www",
      "chgrp --reference=ref.txt file.txt",
    ],
    options: [
      "-R",
      "--recursive",
      "-v",
      "--verbose",
      "-c",
      "--changes",
      "--reference <file>",
      "-h",
      "--no-dereference",
    ],
  },
  {
    command: "umask",
    description: "Standardrechte für neue Dateien anzeigen oder setzen",
    category: "users",
    risk: "safe",
    examples: ["umask", "umask 022", "umask -S"],
    options: ["-S", "-p"],
  },
  {
    command: "groupadd",
    description: "Linux-Gruppe anlegen",
    category: "users",
    risk: "caution",
    examples: [
      "sudo groupadd developers",
      "sudo groupadd -g 1500 app",
      "sudo groupadd -r servicegroup",
    ],
    options: ["-g <gid>", "--gid <gid>", "-r", "--system", "-f", "--force"],
  },
  {
    command: "groupdel",
    description: "Linux-Gruppe löschen",
    category: "users",
    risk: "dangerous",
    examples: ["sudo groupdel oldgroup"],
    options: ["-f", "--force", "-h", "--help"],
  },
  {
    command: "groupmod",
    description: "Linux-Gruppe ändern",
    category: "users",
    risk: "caution",
    examples: [
      "sudo groupmod -n newname oldname",
      "sudo groupmod -g 1501 developers",
    ],
    options: [
      "-n <name>",
      "--new-name <name>",
      "-g <gid>",
      "--gid <gid>",
      "-o",
      "--non-unique",
    ],
  },
  {
    command: "userdel",
    description: "Linux-Benutzer löschen",
    category: "users",
    risk: "dangerous",
    examples: ["sudo userdel olduser", "sudo userdel -r olduser"],
    options: ["-r", "--remove", "-f", "--force", "-Z", "--selinux-user"],
  },
  {
    command: "visudo",
    description: "sudoers-Dateien sicher bearbeiten",
    category: "users",
    risk: "caution",
    examples: [
      "sudo visudo",
      "sudo visudo -c",
      "sudo visudo -f /etc/sudoers.d/app",
    ],
    options: [
      "-c",
      "--check",
      "-f <file>",
      "--file <file>",
      "-q",
      "--quiet",
      "-s",
      "--strict",
    ],
  },
  {
    command: "tcpdump",
    description: "Netzwerkpakete mitschneiden und filtern",
    category: "network",
    risk: "caution",
    examples: [
      "sudo tcpdump -i eth0",
      "sudo tcpdump -i any port 22",
      "sudo tcpdump -w capture.pcap",
    ],
    options: [
      "-i <interface>",
      "-n",
      "-nn",
      "-v",
      "-vv",
      "-w <file>",
      "-r <file>",
      "-c <count>",
      "-s <snaplen>",
    ],
  },
  {
    command: "openssl s_client",
    description: "TLS-Verbindungen und Zertifikate testen",
    category: "network",
    risk: "safe",
    examples: [
      "openssl s_client -connect example.com:443",
      "openssl s_client -connect example.com:443 -servername example.com",
      "openssl s_client -showcerts -connect example.com:443",
    ],
    options: [
      "-connect <host:port>",
      "-servername <name>",
      "-showcerts",
      "-brief",
      "-tls1_2",
      "-tls1_3",
      "-CAfile <file>",
    ],
  },
  {
    command: "resolvectl",
    description: "DNS-Konfiguration und Auflösung prüfen",
    category: "network",
    risk: "safe",
    examples: [
      "resolvectl status",
      "resolvectl query example.com",
      "resolvectl dns",
    ],
    options: [
      "--type <type>",
      "--legend <bool>",
      "--no-pager",
      "--interface <ifname>",
      "-4",
      "-6",
    ],
    subcommands: [
      "status",
      "query <name>",
      "dns",
      "domain",
      "statistics",
      "flush-caches",
    ],
  },
  {
    command: "host",
    description: "DNS-Namen einfach auflösen",
    category: "network",
    risk: "safe",
    examples: ["host example.com", "host -t MX example.com", "host 8.8.8.8"],
    options: ["-t <type>", "-a", "-v", "-4", "-6", "-W <seconds>"],
  },
  {
    command: "nmcli",
    description: "NetworkManager über die CLI steuern",
    category: "network",
    risk: "caution",
    examples: [
      "nmcli device status",
      "nmcli connection show",
      "nmcli radio wifi",
    ],
    options: [
      "-t",
      "--terse",
      "-f <fields>",
      "--fields <fields>",
      "-p",
      "--pretty",
      "-m <mode>",
      "--mode <mode>",
    ],
    subcommands: [
      "device status",
      "device show",
      "connection show",
      "connection up <name>",
      "connection down <name>",
      "radio wifi",
    ],
  },
  {
    command: "ethtool",
    description: "Ethernet-Geräte anzeigen und konfigurieren",
    category: "network",
    risk: "caution",
    examples: [
      "ethtool eth0",
      "sudo ethtool -s eth0 speed 1000 duplex full",
      "ethtool -i eth0",
    ],
    options: [
      "-i",
      "--driver",
      "-S",
      "--statistics",
      "-s",
      "--change",
      "-k",
      "--show-features",
      "-K",
      "--features",
    ],
  },
  {
    command: "iw",
    description: "WLAN-Geräte und Verbindungen prüfen",
    category: "network",
    risk: "caution",
    examples: ["iw dev", "iw dev wlan0 link", "sudo iw dev wlan0 scan"],
    options: [
      "dev",
      "dev <iface> link",
      "dev <iface> scan",
      "dev <iface> station dump",
      "reg get",
    ],
  },
  {
    command: "nmap",
    description: "Hosts und Ports scannen",
    category: "network",
    risk: "caution",
    examples: ["nmap 192.168.1.1", "nmap -p 22,80,443 host", "nmap -sV host"],
    options: [
      "-p <ports>",
      "-sV",
      "-sS",
      "-A",
      "-O",
      "-Pn",
      "-n",
      "--top-ports <n>",
    ],
  },
  {
    command: "tmux",
    description: "Terminal-Sitzungen multiplexen",
    category: "system",
    risk: "safe",
    examples: ["tmux", "tmux new -s work", "tmux attach -t work"],
    options: ["-2", "-f <file>", "-L <socket-name>", "-S <socket-path>", "-u"],
    subcommands: [
      "new -s <name>",
      "attach -t <name>",
      "ls",
      "kill-session -t <name>",
      "split-window",
      "new-window",
      "send-keys",
    ],
  },
  {
    command: "screen",
    description: "Terminal-Sitzungen im Hintergrund halten",
    category: "system",
    risk: "safe",
    examples: ["screen", "screen -S work", "screen -r work"],
    options: [
      "-S <name>",
      "-r <session>",
      "-ls",
      "-dmS <name>",
      "-X <command>",
    ],
  },
  {
    command: "nohup",
    description: "Befehl unabhängig vom Terminal weiterlaufen lassen",
    category: "system",
    risk: "safe",
    examples: ["nohup ./server.sh &", "nohup long-command > output.log 2>&1 &"],
    options: ["--help", "--version"],
  },
  {
    command: "jobs",
    description: "Shell-Jobs anzeigen",
    category: "system",
    risk: "safe",
    examples: ["jobs", "jobs -l", "jobs -p"],
    options: ["-l", "-p", "-r", "-s"],
  },
  {
    command: "fg",
    description: "Shell-Job in den Vordergrund holen",
    category: "system",
    risk: "safe",
    examples: ["fg", "fg %1"],
    options: ["%<job>"],
  },
  {
    command: "bg",
    description: "Shell-Job im Hintergrund fortsetzen",
    category: "system",
    risk: "safe",
    examples: ["bg", "bg %1"],
    options: ["%<job>"],
  },
  {
    command: "disown",
    description: "Shell-Job aus der Job-Tabelle lösen",
    category: "system",
    risk: "safe",
    examples: ["disown", "disown %1", "disown -h %1"],
    options: ["-a", "-h", "-r"],
  },
  {
    command: "pidof",
    description: "Prozess-IDs nach Programmnamen finden",
    category: "system",
    risk: "safe",
    examples: ["pidof sshd", "pidof -s nginx", "pidof -x script.sh"],
    options: [
      "-s",
      "--single-shot",
      "-x",
      "--scripts",
      "-o <pid>",
      "--omit-pid <pid>",
    ],
  },
  {
    command: "pstree",
    description: "Prozessbaum anzeigen",
    category: "system",
    risk: "safe",
    examples: ["pstree", "pstree -p", "pstree -u"],
    options: [
      "-p",
      "--show-pids",
      "-u",
      "--uid-changes",
      "-a",
      "--arguments",
      "-h",
      "--highlight-all",
    ],
  },
  {
    command: "vmstat",
    description: "Speicher-, CPU- und I/O-Statistiken anzeigen",
    category: "system",
    risk: "safe",
    examples: ["vmstat", "vmstat 1", "vmstat -s"],
    options: [
      "-s",
      "--stats",
      "-d",
      "--disk",
      "-w",
      "--wide",
      "-t",
      "--timestamp",
    ],
  },
  {
    command: "iostat",
    description: "CPU- und Blockgeräte-I/O anzeigen",
    category: "system",
    risk: "safe",
    examples: ["iostat", "iostat -xz 1", "iostat -p ALL"],
    options: [
      "-x",
      "--extended",
      "-z",
      "--omit",
      "-d",
      "--device",
      "-p <device>",
      "-m",
      "--megabytes",
    ],
  },
  {
    command: "lscpu",
    description: "CPU-Architektur anzeigen",
    category: "system",
    risk: "safe",
    examples: ["lscpu", "lscpu -J", "lscpu --extended"],
    options: [
      "-J",
      "--json",
      "-e",
      "--extended",
      "-p",
      "--parse",
      "-C",
      "--caches",
    ],
  },
  {
    command: "lsmod",
    description: "Geladene Kernel-Module anzeigen",
    category: "system",
    risk: "safe",
    examples: ["lsmod", "lsmod | grep usb"],
    options: ["--help", "--version"],
  },
  {
    command: "modprobe",
    description: "Kernel-Module laden oder entfernen",
    category: "system",
    risk: "caution",
    examples: [
      "sudo modprobe overlay",
      "sudo modprobe -r module_name",
      "modprobe --show-depends overlay",
    ],
    options: [
      "-r",
      "--remove",
      "-n",
      "--dry-run",
      "-v",
      "--verbose",
      "--show-depends",
      "-a",
      "--all",
    ],
  },
  {
    command: "modinfo",
    description: "Informationen zu Kernel-Modulen anzeigen",
    category: "system",
    risk: "safe",
    examples: [
      "modinfo overlay",
      "modinfo -F filename overlay",
      "modinfo -p module_name",
    ],
    options: [
      "-F <field>",
      "--field <field>",
      "-p",
      "--parameters",
      "-n",
      "--filename",
      "-d",
      "--description",
    ],
  },
  {
    command: "fdisk",
    description: "Partitionstabellen anzeigen und bearbeiten",
    category: "system",
    risk: "dangerous",
    examples: ["sudo fdisk -l", "sudo fdisk /dev/sdX"],
    options: [
      "-l",
      "--list",
      "-x",
      "--list-details",
      "-s <partition>",
      "--getsz <partition>",
      "-u",
      "--units <unit>",
    ],
  },
  {
    command: "parted",
    description: "Partitionen anzeigen und verwalten",
    category: "system",
    risk: "dangerous",
    examples: [
      "sudo parted -l",
      "sudo parted /dev/sdX print",
      "sudo parted /dev/sdX unit MiB print",
    ],
    options: [
      "-l",
      "--list",
      "-s",
      "--script",
      "-a <type>",
      "--align <type>",
      "-m",
      "--machine",
    ],
  },
  {
    command: "fsck",
    description: "Dateisysteme prüfen und reparieren",
    category: "system",
    risk: "dangerous",
    examples: [
      "sudo fsck /dev/sdX1",
      "sudo fsck -n /dev/sdX1",
      "sudo fsck -f /dev/sdX1",
    ],
    options: ["-n", "--no", "-y", "--yes", "-f", "-A", "-M", "-V"],
  },
] satisfies TerminalAutocompleteHelp[];

export const TERMINAL_AUTOCOMPLETE_HELP_BY_COMMAND = new Map(
  TERMINAL_AUTOCOMPLETE_HELP.flatMap((entry) => [
    [entry.command, entry] as const,
    ...(entry.aliases ?? []).map((alias) => [alias, entry] as const),
  ]),
);

const UNSAFE_AUTOCOMPLETE_HELP_SUGGESTION_RE =
  /\b(?:rm\s+(?:-[^\n]*[rf]|--(?:force|recursive|no-preserve-root))|mkfs(?:\.\w+)?|dd\s+(?:if=|of=)|shutdown|poweroff|reboot|halt|iptables\s+-F|nft\s+flush|docker\s+system\s+prune|history\s+-c|userdel\s+-r|find\s+-delete)\b/i;

function normalizeHelpSuggestionToken(token: string) {
  return /^-[A-Za-z]+$/.test(token) ? token : token.toLowerCase();
}

function normalizeHelpSuggestion(command: string) {
  return command.trim().split(/\s+/).map(normalizeHelpSuggestionToken).join(" ");
}

function optionToHelpSuggestionSuffix(option: string) {
  return option
    .replace(/\s+<[^>]+>.*$/, "")
    .replace(/=<[^>]+>.*$/, "")
    .trim();
}

function appendHelpSuggestion(
  candidates: string[],
  seen: Set<string>,
  candidate: string,
) {
  const trimmedCandidate = candidate.trim();
  const normalizedCandidate = normalizeHelpSuggestion(trimmedCandidate);

  if (
    !trimmedCandidate ||
    seen.has(normalizedCandidate) ||
    UNSAFE_AUTOCOMPLETE_HELP_SUGGESTION_RE.test(trimmedCandidate)
  ) {
    return;
  }

  seen.add(normalizedCandidate);
  candidates.push(trimmedCandidate);
}

function buildHelpSuggestions() {
  const candidates: string[] = [];
  const seen = new Set<string>();

  for (const entry of TERMINAL_AUTOCOMPLETE_HELP) {
    if (entry.risk === "dangerous") {
      continue;
    }

    appendHelpSuggestion(candidates, seen, entry.command);

    for (const alias of entry.aliases ?? []) {
      appendHelpSuggestion(candidates, seen, alias);
    }

    for (const subcommand of entry.subcommands ?? []) {
      appendHelpSuggestion(candidates, seen, `${entry.command} ${subcommand}`);
    }

    for (const option of entry.options ?? []) {
      const suffix = optionToHelpSuggestionSuffix(option);
      if (suffix) {
        appendHelpSuggestion(candidates, seen, `${entry.command} ${suffix}`);
      }
    }

    for (const option of entry.globalOptions ?? []) {
      const suffix = optionToHelpSuggestionSuffix(option);
      if (suffix) {
        appendHelpSuggestion(candidates, seen, `${entry.command} ${suffix}`);
      }
    }

    for (const format of entry.commonFormats ?? []) {
      appendHelpSuggestion(candidates, seen, `${entry.command} -o ${format}`);
    }

    for (const [subcommand, options] of Object.entries(
      entry.commandOptions ?? {},
    )) {
      const normalizedSubcommand = subcommand.replace(/_/g, " ");
      for (const option of options) {
        const suffix = optionToHelpSuggestionSuffix(option);
        if (suffix) {
          appendHelpSuggestion(
            candidates,
            seen,
            `${entry.command} ${normalizedSubcommand} ${suffix}`,
          );
        }
      }
    }

    for (const example of entry.examples) {
      appendHelpSuggestion(candidates, seen, example);
    }

    for (const examples of Object.values(entry.commonPatterns ?? {})) {
      for (const example of examples) {
        appendHelpSuggestion(candidates, seen, example);
      }
    }
  }

  return candidates;
}

export const TERMINAL_AUTOCOMPLETE_COMMANDS = buildHelpSuggestions();
